---
- name: Prepare Proxmox Host
  hosts: proxmox_nodes
  become: yes
  tasks:
    - name: Ensure the system is up-to-date
      apt:
        update_cache: yes
        upgrade: dist

    - name: Create isolated network bridge (vmbr1) for Home Lab
      blockinfile:
        path: /etc/network/interfaces
        block: |
          auto vmbr1
          iface vmbr1 inet manual
                  bridge-ports none
                  bridge-stp off
                  bridge-fd 0
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR VMBR1"
      notify: restart_networking

  handlers:
    - name: restart_networking
      command: systemctl restart networking