---
# Inventory for guest VMs created by Terraform.
# The IPs are aligned with terraform/environments/local/locals.tf.
all:
  children:
    guests:
      hosts:
        ubuntu-server:
          ansible_host: 10.10.10.10
          ansible_user: ubuntu
        ubuntu-desktop:
          ansible_host: 10.10.10.11
          ansible_user: ubuntu
