---
# Full desired state of the guest VMs.
# This playbook configures the guests created by Terraform.
#
# Usage:
#   ANSIBLE_CONFIG=ansible.cfg ansible-playbook playbooks/ubuntu_desktop/site.yml
#
- import_playbook: 10-base.yml
